In [6]:
import numpy as np
# create array x
x = np.array([1,2,3,4,5,6,7,8,7,6,5,4])

In [7]:
# print the shape of x
x.shape

(12,)

In [8]:
# create a two dimensional array
y = x.reshape(3,4)

In [9]:
# print shape of 2d array
y.shape

(3, 4)

In [10]:
# reshape the array to 2 x 6
y = y.reshape(2,6)

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 7, 6, 5, 4]])

In [11]:
# reshape the array to 1 x 12
y = y.reshape(1,12)

In [15]:
# transpose the array
y = y.reshape(3,4)
y.T

array([[1, 5, 7],
       [2, 6, 6],
       [3, 7, 5],
       [4, 8, 4]])

In [35]:
# indexing method 1
print y
y[0,2]

[[1 2 3 4]
 [5 6 7 8]
 [7 6 5 4]]


3

In [17]:
# indexing method 2
y[0][2]

3

In [34]:
# indexing method 3
print y[2][:4]

[7 6 5 4]


In [12]:
# indexing method 4

In [11]:
# indexing method 5

In [10]:
# indexing method 6